# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :zabbix => {
        :box_name => "centos/8",
        :ip_addr => '192.168.11.122',		
   },
}

Vagrant.configure("2") do |config|
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	config.vm.box_check_update = false
		MACHINES.each do |boxname, boxconfig|
			config.vm.define boxname do |box|
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxname.to_s
			box.vbguest.installer_options = { allow_kernel_upgrade: true }
			#box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
			box.vm.network "private_network", ip: boxconfig[:ip_addr]
			box.vm.provider :virtualbox do |vb|
				vb.customize ["modifyvm", :id, "--memory", "1024"]
               		end
			box.vm.provision "shell", inline: <<-SHELL
				mkdir -p ~root/.ssh
				cp ~vagrant/.ssh/auth* ~root/.ssh
				sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config;
				systemctl restart sshd;	
			SHELL
			end
		end

	config.vm.define "dzabbix" do |zabbix|
		zabbix.vm.provision "shell", inline: <<-SHELL
		dnf -y install https://repo.zabbix.com/zabbix/5.4/rhel/8/x86_64/zabbix-release-5.4-1.el8.noarch.rpm  
		dnf -y install httpd
		dnf -y install zabbix-server-pgsql zabbix-web-pgsql zabbix-apache-conf zabbix-sql-scripts zabbix-agent
		
		sudo cp /vagrant/zabbix_server.conf.bk /etc/zabbix/zabbix_server.conf
		sudo cp /vagrant/zabbix_agentd.conf.bk /etc/zabbix/zabbix_agentd.conf
		
		sudo systemctl start zabbix-server zabbix-agent httpd php-fpm
        sudo systemctl enable zabbix-server zabbix-agent httpd php-fpm
        
        sudo setsebool -P httpd_can_connect_zabbix on
        sudo setsebool -P httpd_can_network_connect_db on
        sudo ausearch -c 'zabbix_server' --raw | audit2allow -M my-zabbixserver
        sudo semodule -X 300 -i my-zabbixserver.pp
			
       SHELL
	end
 
end









