# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :wordpress => {
        :box_name => "centos/8",
        :ip_addr => '192.168.11.125',		
   },
}

Vagrant.configure("2") do |config|
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	config.vm.box_check_update = false
		MACHINES.each do |boxname, boxconfig|
			config.vm.define boxname do |box|
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxname.to_s
			box.vbguest.installer_options = { allow_kernel_upgrade: true }
			#box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
			box.vm.network "private_network", ip: boxconfig[:ip_addr]
			box.vm.provider :virtualbox do |vb|
				vb.customize ["modifyvm", :id, "--memory", "1024"]
               		end
			box.vm.provision "shell", inline: <<-SHELL
				mkdir -p ~root/.ssh
				cp ~vagrant/.ssh/auth* ~root/.ssh
				sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config;
				systemctl restart sshd;	
			SHELL
			end
		end

	config.vm.define "wordpress" do |wordpress|
		wordpress.vm.provision "shell", inline: <<-SHELL
		
		sudo systemctl stop firewalld
		sudo setenforce 0
		
		sudo dnf -y clean all
		sudo dnf -y install wget
		# Установка LAMP
		sudo dnf install httpd
		sudo systemctl restart httpd
		sudo systemctl enable httpd
		sudo dnf -y install mariadb-server
		sudo systemctl restart mariadb
		sudo systemctl enable mariadb
		sudo dnf -y install php php-common php-pecl-apcu php-cli php-pear php-pdo php-mysqlnd php-pgsql php-gd php-mbstring php-xml  php-json
		sudo systemctl restart httpd
		sudo touch /var/www/html/test.php
		
		echo '<?php' > /var/www/html/test.php
		echo 'phpinfo();' >> /var/www/html/test.php
		echo '?>' >> /var/www/html/test.php
		
		# Установка LAMP закончена
		
		# Установка WordPress
		cp /vagrant/conf_wordpress/latest.tar.gz /var/www/html/
		sudo wget http://wordpress.org/latest.tar.gz -O /var/www/html/latest.tar.gz 
		sudo tar -xzvf /var/www/html/latest.tar.gz  -C /var/www/html/
		sudo chown -R apache:apache /var/www/html
		sudo mv /var/www/html/wordpress/* /var/www/html/
		sudo rm -rf /var/www/html/latest.tar.gz
		sudo rm -rf /var/www/html/wordpress
		
		cp /vagrant/conf_wordpress/wp-config.php.bk /var/www/html/wp-config.php
		chown -R apache:apache /var/www/html
		> /etc/httpd/conf.d/vhosts.conf
		echo 'IncludeOptional vhosts.d/*.conf' > /etc/httpd/conf.d/vhosts.conf
		
		mkdir /etc/httpd/vhosts.d/
		cp /vagrant/conf_wordpress/wordpress.conf.bk /etc/httpd/vhosts.d/wordpress.conf
		
		#Настройка MariaDB
		#mysqladmin -u root password "123456";
		mysql -u root < /vagrant/conf_wordpress/create-db.sql
		
		sudo systemctl restart httpd.service
		sudo systemctl restart php-fpm.service
		sudo systemctl enable php-fpm.service
			
       SHELL
	end
 
end









