# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :masterpostgres=> {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.240'
  },
  :slavepostgres=> {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.241',
  }
 }

Vagrant.configure("2") do |config|
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	config.vm.box_check_update = false
		MACHINES.each do |boxname, boxconfig|
			config.vm.define boxname do |box|
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxname.to_s
			box.vbguest.installer_options = { allow_kernel_upgrade: true }
			box.vm.network "private_network", ip: boxconfig[:ip_addr]
			box.vm.provider :virtualbox do |vb|
				vb.customize ["modifyvm", :id, "--memory", "2048"]
               		end
			box.vm.provision "shell", inline: <<-SHELL
				mkdir -p ~root/.ssh
				cp ~vagrant/.ssh/auth* ~root/.ssh
				sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config;
				systemctl restart sshd;

				adduser ansible
				echo "ansible:ansible" | chpasswd
				usermod -aG wheel ansible
				echo "%ansible ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible

			SHELL
			end
		end

#	config.vm.provision "ansible" do |ansible|
#       ansible.verbose = "vvv"
#		ansible.playbook = "provisioning/playbook.yml"
#		ansible.become = "true"
#	end


config.vm.define "masterpostgres" do |masterpostgres|
		masterpostgres.vm.provision "shell", inline: <<-SHELL

       SHELL
 end

 config.vm.define "slavepostgres" do |slavepostgres|
		slavepostgres.vm.provision "shell", inline: <<-SHELL

       SHELL
 end

end
