# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 1024,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 1024, # Megabytes
			:port => 2
		},
                :sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 1024,
                        :port => 3
                },
                :sata4 => {
                        :dfile => './sata4.vdi',
                        :size => 1024, # Megabytes
                        :port => 4
                }

	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        yum install mdadm smartmontools hdparm gdisk -y
        mdadm --zero-superblock --force /dev/sd{b,c,e,d}
        wipefs --all --force /dev/sd{b,c,d,e}
        mdadm --create --verbose /dev/md0 -l 10 -n 4 /dev/sd{b,c,d,e}
        mkdir /etc/mdadm
        echo "DEVICE partitions" > /etc/mdadm/mdadm.conf
        mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
        parted /dev/md0 -s mklabel gpt
        parted /dev/md0 -s mkpart primary ext4 0% 20%
        parted /dev/md0 -s mkpart primary ext4 20% 40%
        parted /dev/md0 -s mkpart primary ext4 40% 60%
        parted /dev/md0 -s mkpart primary ext4 60% 80%
        parted /dev/md0 -s mkpart primary ext4 80% 100%
        
        for i in $(seq 1 5); do mkfs.ext4 /dev/md0p$i; done
        
        mkdir /mnt/disk-{1,2,3,4,5}
        #for i in $(seq 1 5); do mount /dev/md0p$i /mnt/disk-$i; done
        
        #for i in $(seq 1 5); do echo "/dev/md0p$i        /mnt/disk-$i    ext4    defaults    1 2">>/etc/fstab; done
        
        echo "/dev/md0p1        /mnt/disk-1    ext4    defaults    1 2" >> /etc/fstab
        echo "/dev/md0p2        /mnt/disk-2    ext4    defaults    1 2" >> /etc/fstab
        echo "/dev/md0p3        /mnt/disk-3    ext4    defaults    1 2" >> /etc/fstab
        echo "/dev/md0p4        /mnt/disk-4    ext4    defaults    1 2" >> /etc/fstab
        echo "/dev/md0p5        /mnt/disk-5    ext4    defaults    1 2" >> /etc/fstab
        
        #echo "/dev/md0        /mnt    ext4    defaults    1 2" >> /etc/fstab
        mount -a
      
      
  	  SHELL

      end
  end
end

