# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :vmtest => {
        :box_name => "centos/8",
        :box_version => "2004.01",
		:ip_addr => '192.168.11.222',		
   },
}

Vagrant.configure("2") do |config|
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	# config.vm.box_version = "2004.01"
	config.vm.box_check_update = false
		MACHINES.each do |boxname, boxconfig|
			config.vm.define boxname do |box|
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxname.to_s
			box.vbguest.installer_options = { allow_kernel_upgrade: true }
			#box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
			box.vm.network "private_network", ip: boxconfig[:ip_addr]
			box.vm.provider :virtualbox do |vb|
				vb.customize ["modifyvm", :id, "--memory", "1024"]
               		end
			box.vm.provision "shell", inline: <<-SHELL
				mkdir -p ~root/.ssh
				cp ~vagrant/.ssh/auth* ~root/.ssh
				sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config;
				systemctl restart sshd;	
		
			SHELL
			end
		end

	config.vm.define "vmtest" do |vmtest|
		vmtest.vm.provision "shell", inline: <<-SHELL
		dnf -y install epel-release
		# Установка необходимых пакетов для работы с SE Linux
		dnf -y install setools-console 
		dnf -y install policycoreutils-python-utils 
		dnf -y install policycoreutils-newrole 
		dnf -y install selinux-policy-mls
		dnf -y install setroubleshoot-server
		
		# Установка nginx
        yum -y install nginx
		# Перенос конфигурационный файл nginx.conf с нестандартным портом
		cp /vagrant/nginx.conf /etc/nginx/
		# Настраиваем автозапуск nginx при запуске ОС, но не запускаем nginx. Все равно будет ошибка
		systemctl enable nginx
		#systemctl start nginx	

		
       SHELL
	end
 
end









