# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :vmtest => {
        :box_name => "centos/8",
        #:box_version => "2004.01",
		:ip_addr => '192.168.11.191',		
   },
}

Vagrant.configure("2") do |config|
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	#config.vm.box_version = "2004.01"
	config.vm.box_check_update = false
		MACHINES.each do |boxname, boxconfig|
			config.vm.define boxname do |box|
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxname.to_s
			box.vbguest.installer_options = { allow_kernel_upgrade: true }
			#box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
			box.vm.network "private_network", ip: boxconfig[:ip_addr]
			
			box.vm.provider :virtualbox do |vb|
				vb.customize ["modifyvm", :id, "--memory", "1024"]
            end
			
#			box.vm.provision "shell", inline: <<-SHELL
#				
#			SHELL
			end
		end
	config.vm.provision :shell, path: "script1.sh", run: 'always'
	config.vm.provision :shell, path: "script2.sh", run: 'always'

	config.vm.define "vmtest" do |vmtest|
	vmtest.vm.provision "shell", inline: <<-SHELL
	yum install epel-release -y
	yum install python36 -y
	yum install ansible	-y		
	sudo cp /vagrant/ansible.cfg /etc/ansible/	
    SHELL
	end

	config.vm.provision "ansible_local" do |ansible|
    ansible.become = true
    ansible.provisioning_path = "/vagrant"
    ansible.playbook = "nginx.yml"
    ansible.inventory_path = "/vagrant/inventories/hosts"  
    ansible.limit = "all"
#	ansible.verbose = "vvv"
#   ansible.install = true
#   vagrant_synced_folder_default_type = ""
    end



 
end







   

