# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :vmrepo => {
        :box_name => "centos/7",
        :box_version => "2004.01",
        :ip_addr => '192.168.11.201',
  },
}

Vagrant.configure("2") do |config|
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	config.vm.box_version = "2004.01"
	config.vm.box_check_update = false
		MACHINES.each do |boxname, boxconfig|
			config.vm.define boxname do |box|
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxname.to_s
			box.vbguest.installer_options = { allow_kernel_upgrade: true }
			#box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
			box.vm.network "private_network", ip: boxconfig[:ip_addr]
			box.vm.provider :virtualbox do |vb|
				vb.customize ["modifyvm", :id, "--memory", "1024"]
               		end
			box.vm.provision "shell", inline: <<-SHELL
            
				mkdir -p ~root/.ssh
				cp ~vagrant/.ssh/auth* ~root/.ssh
				sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config;
				systemctl restart sshd;	
				
                adduser asarafanov 
                echo "asarafanov:Margo@99" | chpasswd
                usermod -aG wheel asarafanov
                echo "%asarafanov ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/asarafanov
                
 				yum install -y kernel*		
				
			SHELL
			end
		end

	config.vm.define "vmrepo" do |vmrepo|
		vmrepo.vm.provision "shell", inline: <<-SHELL
 		
		sudo useradd builder -m
		
		sudo yum install -y epel-release
		sudo yum install -y rpm-build rpmdevtools yum-utils openssl-devel zlib-devel pcre-devel redhat-lsb-core 
        sudo yum install -y git  gcc make automake yum-utils wget createrepo 
		
        cd /root
        
		sudo yum-builddep -y nginx 
		
cat << EOF | sudo tee /etc/yum.repos.d/nginx.repo
[nginx-stable]
name=nginx stable repo
baseurl=http://nginx.org/packages/centos/7/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://nginx.org/keys/nginx_signing.key
module_hotfixes=true
EOF
		sudo mkdir /root/modules
		
		sudo wget https://www.openssl.org/source/latest.tar.gz -O /root/modules/latest.tar.gz
		cd /root/modules
		tar -xvf /root/modules/latest.tar.gz 
		
		
		cd /root
		sudo wget http://nginx.org/packages/centos/7/SRPMS/nginx-1.20.1-1.el7.ngx.src.rpm -O /root/nginx-1.20.1-1.el7.ngx.src.rpm
		sudo rpmdev-setuptree 
		sudo rpm -ivh nginx-1.20.1-1.el7.ngx.src.rpm 
		sudo wget https://raw.githubusercontent.com/Aleksey-10081967/HomeWork/main/HW-lesson-06/nginx.spec -O /root/rpmbuild/SPECS/nginx.spec
        sudo rpmbuild -ba rpmbuild/SPECS/nginx.spec 
		sudo yum localinstall -y /root/rpmbuild/RPMS/x86_64/nginx-1.20.1-1.el7.ngx.x86_64.rpm
        sudo systemctl start nginx
        sudo systemctl status nginx
		
        sudo mkdir /usr/share/nginx/html/repo
		sudo cp /root/rpmbuild/RPMS/x86_64/nginx-1.20.1-1.el7.ngx.x86_64.rpm  /usr/share/nginx/html/repo/
		sudo wget http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm -O /usr/share/nginx/html/repo/percona-release-0.1-6.noarch.rpm
		sudo wget http://mirror.centos.org/centos/7/updates/x86_64/Packages/httpd-2.4.6-97.el7.centos.x86_64.rpm -O /usr/share/nginx/html/repo/httpd-2.4.6-97.el7.centos.x86_64.rpm
	    
		sudo createrepo /usr/share/nginx/html/repo/
	
cat << EOF | sudo tee /etc/yum.repos.d/otus.repo
[otus]
name=otus-linux
baseurl=http://192.168.11.201/repo
enabled=1
gpgcheck=0
EOF


cat << EOF | sudo tee /etc/nginx/conf.d/default.conf
server {
    listen       80;
    server_name  localhost;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        autoindex on;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
       root   /usr/share/nginx/html;
   }
}
EOF
sudo nginx -s reload        
      
        
       SHELL
	end

end









