# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nfsserver => {
        :box_name => "centos/7",
        :box_version => "2004.01",
        :ip_addr => '192.168.11.101',
  },
  :nfsclient => {
        :box_name => "centos/7",
        :box_version => "200.01",
        :ip_addr => '192.168.11.102',
  },
}

Vagrant.configure("2") do |config|
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	config.vm.box_version = "2004.01"
	config.vm.box_check_update = false
		MACHINES.each do |boxname, boxconfig|
			config.vm.define boxname do |box|
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxname.to_s
			box.vbguest.installer_options = { allow_kernel_upgrade: true }
			#box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
			box.vm.network "private_network", ip: boxconfig[:ip_addr]
			box.vm.provider :virtualbox do |vb|
				vb.customize ["modifyvm", :id, "--memory", "1024"]
               		end
			box.vm.provision "shell", inline: <<-SHELL
				mkdir -p ~root/.ssh
				cp ~vagrant/.ssh/auth* ~root/.ssh
				sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config;
				systemctl restart sshd;	
		echo "Выполняем обновление kernel"
				yum install -y kernel*				
			SHELL
			end
		end

	config.vm.define "nfsserver" do |nfsserver|
		nfsserver.vm.provision "shell", inline: <<-SHELL
            setenforce 0
            echo SELINUX=disabled > /etc/selinux/config
            yum install nfs-utils nfs-utils-lib -y
            systemctl enable rpcbind nfs-server nfs-lock nfs-idmap
            systemctl start rpcbind nfs-server nfs-lock nfs-idmap
            mkdir -p /mnt/share/upload
            chmod -R 777 /mnt/share/
            echo "/mnt/share 192.168.11.102(rw,sync,no_root_squash,no_all_squash)" > /etc/exports
            exportfs -r
            sysemctl restart nfs-server
            systemctl start firewalld
            systemctl enable firewalld
            firewall-cmd --permanent --zone=public --add-service=nfs
            firewall-cmd --permanent --zone=public --add-service=mountd
            firewall-cmd --permanent --zone=public --add-service=rpc-bind
            firewall-cmd --permanent --add-port=111/tcp
            firewall-cmd --permanent --add-port=20048/tcp
            firewall-cmd --permanent --add-port=4001/tcp
            firewall-cmd --permanent --add-port=4001/udp
            firewall-cmd --permanent --add-port=2049/udp
            firewall-cmd --permanent --add-port=2049/tcp
            firewall-cmd --reload
            firewall-cmd --runtime-to-permanent
            selinuxenabled 1
            
       SHELL
	end
       config.vm.define "nfsclient" do |nfsclient|
		nfsclient.vm.provision "shell", inline: <<-SHELL
            yum install nfs-utils -y
            systemctl enable rpcbind
            systemctl restart rpcbind
            mkdir -p /mnt/nfs-share
            echo "192.168.11.101:/mnt/share /mnt/nfs-share        nfs     noauto,x-systemd.automount,rw,sync,hard,intr,nfsvers=3,udp    0       0" >> /etc/fstab
            reboot
        SHELL
       end

end









